version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  db:
    image: postgres:12.2
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - local/environment


  django:
    build:
      context: .
      args:
        DEVEL: "yes"
    image: elevennote_local_django
    depends_on:
      - db
      - mailhog
    command: python manage.py migrate && python manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - ./elevennote:/opt/elevennote:z
    env_file: local/environment
    links:
      - db
      - mailhog
    ports:
      - "8000:8000"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"