version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  db:
    image: 'postgres:12.2'
    volumes:
      - 'local_postgres_data:/var/lib/postgresql/data'
      - 'local_postgres_data_backups:/backups'
    env_file:
      - local/environment

  django:
    build:
      context: .
      args:
        DEVEL: 'yes'
    image: elevennote_local_django:dev
    command: python manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - './elevennote:/opt/elevennote:z'
    env_file:
      - local/environment
    depends_on:
      - migrate
      - mailhog
    links:
      - db
      - mailhog

  migrate:
    build:
      context: .
      args:
        DEVEL: 'yes'
    image: elevennote_local_django:dev
    command: python manage.py migrate
    volumes:
      - './elevennote:/opt/elevennote:z'
    env_file:
      - local/environment
    depends_on:
      - db
    links:
      - db
  front-end:
    image: 'node:13-buster-slim'
    user: node
    working_dir: /opt/project
    environment:
      - BROWSER=none
    command: npm start
    volumes:
      - './front-end:/opt/project:z'
    depends_on:
      - front-end-install
    stdin_open: true
  front-end-install:
    image: 'node:13-buster-slim'
    user: node
    working_dir: /opt/project
    volumes:
      - './front-end:/opt/project:z'
    command: npm install
  mailhog:
    image: 'mailhog/mailhog:v1.0.0'
